---
payload:
  description: "Sensor specific settings, simulate hosts payload."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    entries:
      type: "array"
      description: 'list of hosts: [{"hostname":"foo", "mount":"/var/log"}]'
      items:
        type: "object"
      required: false
      additionalProperties: true

debounce_alerts_root_file_path:
  description: "Root file path for storing debounced alerts."
  type: "string"
  required: false 
  default: "/opt/stackstorm/packs/incident_reduction/packdata/debounce_alerts"

debounce_time_in_seconds:
  description: "Time in seconds to debounce alerts."
  type: "integer"
  required: false
  default: 20