---
name: handle-alerts
description: Handle alerts
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
      url: "handle-alerts"

action:
    ref: incident_reduction.handle-alerts
    parameters:
      trigger_data: "{{trigger.body}}"

      # can get specific and make fields required in the action metadata file
      # type:  "{{trigger.body.type}}"
      # actor: "{{trigger.body.actor}}"
      # id: "{{trigger.body.id}}"
