---
name: handle-alerts
description: Handle alerts
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
      url: "handle-alerts"

action:
  ref: examples.notify-inquiries
  parameters:
    inquiry_data: "{{ trigger }}"

action:
    ref: incident_reduction.handle-alerts
    parameters:
      trigger_data: "{{trigger.body}}"
