---
name: handle-process-debounce-alerts
description: Handle triggers from process_debounce_alerts sensor
enabled: true

trigger:
  type: incident_reduction.processed_debounced_alerts

action:
    ref: incident_reduction.handle-processed-debounced-alerts
    parameters:
      trigger_data: "{{trigger}}"

      # can get specific and make fields required in the action metadata file
      # type:  "{{trigger.body.type}}"
      # actor: "{{trigger.body.actor}}"
      # id: "{{trigger.body.id}}"
